/* Example database setup - do not edit this file!

   Use this as an example to create your local appname_db_setup.sql file - containing your mysql secrets
   (Use the filename that's in the .gitignore)

   Then as superadmin or root user, run your local db_setup file from the command line
   mysql -p < appname_db_setup.sql
   (or user your preferred mysql client)
 */

DROP DATABASE IF EXISTS dbname;

CREATE DATABASE IF NOT EXISTS dbname;

USE dbname;

CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON dbname.* TO 'username'@'localhost';